apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  annotations:
    traffic.sidecar.istio.io/includeOutboundIPRanges: "NET_SCOPE"
  name: twitter-source
spec:
  args:
  - --query=knative
  env:
  - name: T_CONSUMER_KEY
    valueFrom:
      secretKeyRef:
        key: T_CONSUMER_KEY
        name: ktweet-secrets
  - name: T_CONSUMER_SECRET
    valueFrom:
      secretKeyRef:
        key: T_CONSUMER_SECRET
        name: ktweet-secrets
  - name: T_ACCESS_TOKEN
    valueFrom:
      secretKeyRef:
        key: T_ACCESS_TOKEN
        name: ktweet-secrets
  - name: T_ACCESS_SECRET
    valueFrom:
      secretKeyRef:
        key: T_ACCESS_SECRET
        name: ktweet-secrets
  image: us.gcr.io/knative-samples/ktweets:latest
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Broker
    name: default
