apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: twitter-source
spec:
  args:
    - --query=google
  env:
    - name: RELEASE
      value: "v0.1.9"
    - name: T_CONSUMER_KEY
      valueFrom:
        secretKeyRef:
          key: T_CONSUMER_KEY
          name: ktweet-secrets
    - name: T_CONSUMER_SECRET
      valueFrom:
        secretKeyRef:
          key: T_CONSUMER_SECRET
          name: ktweet-secrets
    - name: T_ACCESS_TOKEN
      valueFrom:
        secretKeyRef:
          key: T_ACCESS_TOKEN
          name: ktweet-secrets
    - name: T_ACCESS_SECRET
      valueFrom:
        secretKeyRef:
          key: T_ACCESS_SECRET
          name: ktweet-secrets
  image: gcr.io/cloudylabs-public/ktweet:0.1.10
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Broker
    name: default
