apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  annotations:
    traffic.sidecar.istio.io/includeOutboundIPRanges: "INCLUDE_OUTBOUND_IPRANGES"
  name: twitter-test
spec:
  args:
  - --query=QUERY
  - --stream=true
  env:
  - name: TWITTER_CONSUMER_KEY
    valueFrom:
      secretKeyRef:
        key: consumer-key
        name: twitter-secret
  - name: TWITTER_CONSUMER_SECRET_KEY
    valueFrom:
      secretKeyRef:
        key: consumer-secret-key
        name: twitter-secret
  - name: TWITTER_ACCESS_TOKEN
    valueFrom:
      secretKeyRef:
        key: access-token
        name: twitter-secret
  - name: TWITTER_ACCESS_SECRET
    valueFrom:
      secretKeyRef:
        key: access-secret
        name: twitter-secret
  image: us.gcr.io/probable-summer-223122/source-7dd4982354a958712ad81ca4a42243dd@sha256:d783e702e953b5122c47d25ce05576d51cf8d76d40e33c3544c06079cf8dac96
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Broker
    name: default

---
