apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: twitter-trigger
spec:
  filter:
    sourceAndType:
      type: com.twitter
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: tweets
